### ISSUE TITLE
Developer console new application button is grayed out

### ISSUE THREAD

**Issue by jkainul** [trimble-oss/trimble-id-sdk-docs-for-net#9]
Documentation here points to developer console but the new application button is grayed out for me. https://github.com/trimble-oss/trimble-id-sdk-docs-for-net
The instructions don't provide any help with this matter.

**Comment by vineshparamasivam** [comment]
@jkainul the link points to v3 developer console, which will be EOL soon. please use https://console.trimble.com/ to create new application. We will fix this link in the documentation
